/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laipengxu_cputypelibfactory_CpuTypeUtils */

#ifndef _Included_com_laipengxu_cputypelibfactory_CpuTypeUtils
#define _Included_com_laipengxu_cputypelibfactory_CpuTypeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isArmCpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isArmCpu
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isArm7Compatible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isArm7Compatible
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isMipsCpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isMipsCpu
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isX86Cpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isX86Cpu
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isArm64Cpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isArm64Cpu
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isMips64Cpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isMips64Cpu
  (JNIEnv *, jclass);

/*
 * Class:     com_laipengxu_cputypelibfactory_CpuTypeUtils
 * Method:    isX86_64Cpu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_laipengxu_cputypelibfactory_CpuTypeUtils_isX86_164Cpu
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
